### ISSUE TITLE
WP Meetup Hamburg - herausfiltern klappt nicht

### ISSUE THREAD

**Issue by Zodiac1978** [deworg/wpmg-widget#11]
Die Option mit dem Herausfiltern des eigenen Meetups klappt beim Meetup Hamburg nicht. Womöglich, weil es mit "www" läuft aber ohne im Plugin eingetragen ist.

**Comment by 2ndkauboy** [comment]
Habt ihr etwa schon wieder eure URL angepasst? :)

**Comment by Zodiac1978** [comment]
Vielleicht bei der Umstellung auf https passiert? @drivingralle weiß das vielleicht.

**Comment by Zodiac1978** [comment]
Das Update ist eingespielt, aber er filtert immer noch nicht. Werden die Widget-Ausgaben WP intern gecached? Ein Cache-Plugin ist bei uns sonst nicht im Einsatz ...
