### ISSUE TITLE
Github Action einrichten für automatischen SVN Commit bei Release

### ISSUE THREAD

**Issue by Zodiac1978** [deworg/wpmg-widget#21]
Das Pluginkollektiv nutzt diese Technik sehr erfolgreich und sie spart wahnsinnig viel Arbeit.

Im offiziellen Verzeichnis ist es momentan als veraltet markiert und nur bis 4.9 kompatibel.
https://wordpress.org/plugins/wpmeetup-widget/

Das sollte mal auf den aktuellen Stand gebracht werden.

**Comment by 2ndkauboy** [comment]
Wurde in den `stable` Branch gemerged und kann dort ab sofort benutzt werden.
