### ISSUE TITLE
Kompatibilität mit Block-Editor/Site-Editor?

### ISSUE THREAD

**Issue by Zodiac1978** [deworg/wpmg-widget#22]
Hat jemand das Plugin ohne "Classic Widget"-Plugin im Einsatz? Gibt es Probleme? Kann/Muss das Plugin als Block gebaut werden für die Zukunft?

**Comment by espiat** [comment]
hi.

Läuft hier ohne "Classic Widget" tadelllos.
Aber das hab ich auch erwartet.

**Comment by Zodiac1978** [comment]
Bei uns in Hamburg auch. Mir ist nur aufgefallen, dass keine Übersetzung vorhanden ist. Sowohl "Title" als auch "Filter own meetup" ist nicht übersetzt.
