### ISSUE TITLE
Übersetzung fehlt

### ISSUE THREAD

**Issue by Zodiac1978** [deworg/wpmg-widget#23]
Der Text im Widget ist nicht übersetzt (Title und Filter own meetup).

Auf der [Übersetzungsseite](url) wird auch ein Fehler angezeigt:
> This plugin is not [properly prepared for localization](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/). If you would like to translate this plugin, [please contact the author](https://wordpress.org/support/plugin/wpmeetup-widget).

**Comment by Zodiac1978** [comment]
Der Slug ist ja `wpmeetup-widget`, daher müsste die Textdomain auch so heißen und nicht `wpmg-widget`.

**Comment by Zodiac1978** [comment]
Text Domain ist im PR auch gefixt, das dürfte es (auch) gewesen sein laut `#meta-language-packs`
> Plugin is not compatible with language packs: Missing text domain in header.

**Comment by espiat** [comment]
wie geil ist den der name von dem milestone.
JAAAA
