### ISSUE TITLE
Tested up to hochsetzen

### ISSUE THREAD

**Issue by Zodiac1978** [deworg/wpmg-widget#25]
Aktuell hat das Plugin auf WordPress.org die Warnung:

> This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

Und ist seit 5 Jahren nicht aktualisiert worden. Läuft bei uns in Hamburg aber ohne Probleme (abgesehen von den offenen Issues) prinzipiell mit der aktuellen WP-Version.

**Comment by 2ndkauboy** [comment]
Fixed in 1a7a1e9aff4eb3fc9b7bca84ebb5b703451f7662
