### ISSUE TITLE
Ausfilterung des eigenen Meetup-Links abhängig von http/https

### ISSUE THREAD

**Issue by stkjj** [deworg/wpmg-widget#6]
Wenn http - dann eigenes Meetup (Franken) nicht angezeigt
wenn https - dann Franken mit in der Liste

**Comment by 2ndkauboy** [comment]
Ist damit nur euer Meetup gemeint? Das Widget wurde so programmiert, dass das Meetup, auf dem es eingebunden ist, nicht angezeigt wird (es wird die exalte Domain inkl. Protokoll verglichen).

Oder hast du den Effekt auch auf einer anderen Seite gesehen? Also bei Meetup von Stuttgart (HTTP) ist Franken genauso gelistet wie beim Meetup Berlin (HTTPS).

**Comment by stkjj** [comment]
Moin,

> Ist damit nur euer Meetup gemeint? Das Widget wurde so programmiert, dass das Meetup, auf dem es eingebunden ist, nicht angezeigt wird (es wird die exalte Domain inkl. Protokoll verglichen).

genau. Das mit dem exakten Protokoll ist das Thema.

Gruß Stefan

**Comment by 2ndkauboy** [comment]
Und du möchtest, dass das Widget auch auf der eigenen Seite auf sich selbst verlinkt?

**Comment by stkjj** [comment]
Nope. Besser wäre, wenn beide Varianten gefiltert würden. Die Luxusversion wäre ein Schalter ob das eigene Meetup gelistet wird oder nicht.

**Comment by 2ndkauboy** [comment]
Na es sollte ja nur eine gültige URL geben und nicht beide Protokolle. Aber eine Option überlege ich noch einzubauen. Wollte es eben so performant und minimalistisch wie möglich schreiben.

**Comment by krafit** [comment]
Das Prüfen nach Seiten, die sowohl mit als auch ohne SSL erreichbar sind ist imho kein Thema, auf das wir wirklich Zeit verwenden sollten.
Seiten sollten nur unter einem Protokoll erreichbar sein (am Besten HTTPS).
Ein Schalter für die optionale Anzeige des eigenen Meetups ist aber eine gute Idee.

**Comment by 2ndkauboy** [comment]
Ich denke auch, dass nur eine Variante zugelassen sein sollte. Die Checkbox zum Ausfiltern füge ich aber noch hinzu.

Ich bin auch etwas überrascht/enttäuscht, dass aktuell erst 5 Meetups ihre Seite per HTTPS ausliefern. Da sollten wir mehr Vorreiter sein :)

**Comment by staude** [comment]
Denke ich auch. Wenn man SSL zur Verfügung hat sollte man bei nicht SSL Aufrufen direkt redirecten.
oder @stkjj ?
