### ISSUE TITLE
Vorbereitung für w.org Release

### ISSUE THREAD

**Issue by krafit** [deworg/wpmg-widget#7]
Unabhängig von der langen Feature-Wunschliste würde ich dieses Plugin gern bald im w.org-Repo sehen. 

Was müssen wir noch unbedingt erledigen, bevor wir das machen können, @2ndkauboy?

**Comment by 2ndkauboy** [comment]
Ich sehe keinen Grund, es nicht schon ins w.org Repo zu stellen.

**Comment by krafit** [comment]
Aktuell kommen wir sogar noch ohne Übersetzung aus, oder? Werden wir langfristig aber vermutlich brauchen. 
Und wie schauts mit der Readme aus?

**Comment by 2ndkauboy** [comment]
Ich denke auch, dass wir keine Übersetzung brauchen. Die kann sann aber hoffentlich zeitnah über GlotPress eingepflegt werden.

Bei der Readme müssten wir nur den Teil zur Installation entfernen/anpassen. Ansonsten kann ja w.org auch mit Markdown umgehen.

**Comment by 2ndkauboy** [comment]
Das Plugin wurde veröffentlicht: https://wordpress.org/plugins/wpmeetup-widget/
