### ISSUE TITLE
Optionen zur Steuerung der Link-Attribute hinzufügen?

### ISSUE THREAD

**Issue by 2ndkauboy** [deworg/wpmg-widget#8]
Ich bin ja ein strikter Gegner von `target="_blank"`, aus [guten Gründen](https://css-tricks.com/use-target_blank/). Aktuell öffnen aber alle Links standardmäßig in einem neuen Fenster/Tab. Entweder wir können uns darauf einigen, dass die Links immer im aktuellen Fenster öffnen, oder aber ich baue eine Option ein, mit der jeder Steuern kann, wie die Links geöffnet werden sollen. Auch für die Angabe `rel="nofollow"` könnte man eine solche Option anbieten. Was meint ihr dazu?

**Comment by staude** [comment]
Mag ebenfalls nicht die Bevormundung wo ein Link öffnet, das möchte ich selbst entscheiden.
nofollow Option find ich gut.

**Comment by krafit** [comment]
Lasst uns etwas an Optionen sparen: 
Alle Links öffnen immer im gleichen Tab und haben immer nofollow - Punkt :)

**Comment by 2ndkauboy** [comment]
Also für mich gibt es auch keinen Grund, wieso Links nofollow sein sollten. Vertrauten wir denn etwa den anderen Meetups nicht? :)

Aber ich könnte zur Not noch damit leben, wenn ihr es erhalten wollt. Auf meiner Seite ist kein einzige Link nofollow.

**Comment by staude** [comment]
Mach nen Filter und wer nofollow will kann es sich anflanschen

**Comment by krafit** [comment]
+1

**Comment by 2ndkauboy** [comment]
OK, dann mache ich einfach nen Filter für alle Link-Attribute. Da könnt ihr dann auch wieder `target` verwenden, wenn ihr denn meint es zu brauchen :)
